server:
  port: 8080
  servlet:
    context-path: /eduhub
jwt:
  secret: test
  lifetime: 30m
spring:
  application:
    name: eduhub
  datasource:
    url: jdbc:postgresql://localhost:5432/eduhub_db?useSSL=false
    username: bestuser
    password: admin
  jpa:
    show-sql: true
